services:
  backend:
    build:
      dockerfile: dockerfiles/Dockerfile.backend
      target: dev
    ports:
      - 3001:3001
    volumes:
      - ./src/server/:/app/
      - ./src/types/:/app/types/
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json

  frontend:
    build:
      dockerfile: dockerfiles/Dockerfile.frontend
      target: dev
    depends_on:
      - backend
    ports:
      - 5173:5173
    volumes:
      - ./src/client/:/app/
      - ./src/types/:/app/types/
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules/:/app/node_modules/
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
